### ISSUE TITLE
Absorb Escape Implementation

### ISSUE THREAD

**Issue by azuresky03** [Zehui127/Latent-DNA-Diffusion#6]
Hi author,

Thanks for the amazing work. I have read the newer version of your work and noticed that Absorb Escape Implementation could greatly improve performance. Could you please clarify this part of the implementation in the repo? If you haven't done it yet, do you plan to release it in the future, thanks.

**Comment by Zehui127** [comment]
Absorb and Escape is not in this repo as the paper is currently going through the review process. We might release it upon the publication of the paper.

**Comment by azuresky03** [comment]
Thanks for your answer!
